### ISSUE TITLE
Mockups review

### ISSUE THREAD

**Issue by nidalaa** [talihomz/FakeBook#2]

**Comment by nidalaa** [comment]
First you should build the simplest but working app, some kind of MVP :slightly_smiling_face:
That’s why, I’d recommend limit yourselves to the core features.

E.g. in requirements, you can see:
>The Friend Request shows up in the notifications section of a User’s navbar.

So, for the version 1, I suggest just displaying all Friendships with status `pending` and

Also images: let’s add paperclip in version 2, for version 1 skip images for posts.
And for avatar, do not save anything in DB - just display gravatar based on email: https://www.railstutorial.org/book/sign_up#sec-a_gravatar_image.

All my comments on diagrams:

V1

![fakebook erd v1 copy](https://user-images.githubusercontent.com/7466903/39243228-1a0fed06-488d-11e8-9634-fe48ff72af04.jpeg)


V2

![fakebook erd v2 copy](https://user-images.githubusercontent.com/7466903/39243237-1eedf142-488d-11e8-92ca-5f46df77227f.jpeg)

**Comment by talihomz** [comment]
We can now close this since all changes have been implemented in current develop branch
